### ISSUE TITLE
Is the project still being maintained, or are there any new plans for updates?

### ISSUE THREAD

**Issue by wongyan-data** [codefuse-ai/ModelCache#45]
Is the project still being maintained, or are there any new plans for updates?

**Comment by peng3307165** [comment]
Thank you for your attention, this project will continue to be maintained and updated. Due to some urgent reasons, updates have been slow over the past months, but there will be a series of updates coming next, including:
--Add ModelCache Adapter
--Add fastapi service
--Add Docker file
--Better embedding model support
--Ranker logic

Regarding multimodal caching:
--Supports multimodal cacheing.
--comprehensive multimodal caching document.

If you're interested in this project, we welcome you to join our open-source efforts.
Best wishes!
